// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FirstUdemyTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void firstUdemy() {
    driver.get("https://www.udemy.com/");
    driver.manage().window().setSize(new Dimension(1237, 775));
    driver.findElement(By.cssSelector(".header--gap-auth-button--7KoL0 > .udlite-btn-secondary > span")).click();
    driver.findElement(By.id("email--1")).sendKeys("3758289@mail.ru");
    driver.findElement(By.id("id_password")).sendKeys("test123");
   // driver.findElement(By.id("u_0_i_aL")).click();
    driver.findElement(By.id("email")).click();
    driver.findElement(By.id("email")).sendKeys("23456789");
    driver.findElement(By.id("pass")).click();
    driver.findElement(By.id("pass")).sendKeys("34567890");
    driver.findElement(By.id("loginbutton")).click();
    {
      WebElement element = driver.findElement(By.id("loginbutton"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
  }
}
